include ../../build.ini
.PHONY: build
build:
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c list.cpp 	  -o $(OBJECT_BUILD_PATH)/obj/list.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c string.cpp 	  -o $(OBJECT_BUILD_PATH)/obj/string.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c cstring.cpp   -o $(OBJECT_BUILD_PATH)/obj/cstring.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c cmath.cpp 	  -o $(OBJECT_BUILD_PATH)/obj/cmath.o