[SECTION .s64]
[BITS 64]
%define ZERO 0
%define ERROR_CODE 1
[SECTION .data]
EXTERN generalInterruptHandler
[SECTION .text]
save_to_stack:
	PUSH RAX
	PUSH RBX
	PUSH RCX
	PUSH RDX
	PUSH RBP
	PUSH RSI
	PUSH RDI
	PUSH R8
	PUSH R9
	PUSH R10
	PUSH R11
	PUSH R12
	PUSH R13
	PUSH R14
	PUSH R15				 ; 将所有寄存器压入栈
    MOV RDI, RSP
    CALL generalInterruptHandler ; 跳转至通用处理函数
	JMP restore_to_stack

[SECTION .text]
restore_to_stack:
	MOV RSP, RAX
	POP R15
	POP R14
	POP R13
	POP R12
	POP R11
	POP R10
	POP R9
	POP R8
	POP RDI
	POP RSI
	POP RBP
	POP RDX
	POP RCX
	POP RBX
	POP RAX
	ADD RSP, 16
	; 恢复寄存器
	STI ; 开中断
	IRET
%macro HANDLE_ENTRY 2
[SECTION .text]
GLOBAL interruptHandler0x%1
interruptHandler0x%1:
	CLI ; 关中断
	; 有错误码就不动，无错误码就压入0
    %ifn %2
      PUSH QWORD 0
    %endif
    PUSH QWORD 0x%1 ; 压入irq
    JMP  save_to_stack
%endmacro
HANDLE_ENTRY 00, ZERO 	    ;	#DE	除以0
HANDLE_ENTRY 01, ZERO 	    ;	#DB	调试
HANDLE_ENTRY 02, ZERO 	    ;	--- NUM中断
HANDLE_ENTRY 03, ZERO 	    ;	#BP	断点
HANDLE_ENTRY 04, ZERO 	    ;	#OF 溢出
HANDLE_ENTRY 05, ZERO 	    ;	#BR 数组索引超限
HANDLE_ENTRY 06, ZERO 	    ;	#UD	未定义指令
HANDLE_ENTRY 07, ZERO 	    ;	#NM	设备未就绪
HANDLE_ENTRY 08, ERROR_CODE ;	#DF	双重错误
HANDLE_ENTRY 09, ZERO       ;   --- 协处理器错误
HANDLE_ENTRY 0a, ERROR_CODE ;	#TS	无效的TSS
HANDLE_ENTRY 0b, ERROR_CODE ;	#NP	段不存在
HANDLE_ENTRY 0c, ERROR_CODE ;	#SS 堆栈段故障
HANDLE_ENTRY 0d, ERROR_CODE ;	#GP 一般保护故障
HANDLE_ENTRY 0e, ERROR_CODE ;	#PF	缺页
HANDLE_ENTRY 0f ,ZERO       ;   --- intel保留，请勿使用
HANDLE_ENTRY 10, ZERO 	    ;	#MF	x87浮点数异常
HANDLE_ENTRY 11, ERROR_CODE ;	#AC 内存数据引用未对齐 仅在Ring3触发
HANDLE_ENTRY 12, ZERO 	    ;	#MC	处理器内部错误
HANDLE_ENTRY 13, ZERO 	    ;	#XM	SIMD浮点数异常
HANDLE_ENTRY 14, ZERO       ;   #CP 处理器内部错误
HANDLE_ENTRY 15, ERROR_CODE ;   #HV 虚拟机注入的异常
HANDLE_ENTRY 16, ZERO       ;   #VC VMM 通信失败
HANDLE_ENTRY 17, ZERO       ;   #SX 安全异常
HANDLE_ENTRY 18, ZERO
HANDLE_ENTRY 19, ZERO
HANDLE_ENTRY 1a, ZERO
HANDLE_ENTRY 1b, ZERO
HANDLE_ENTRY 1c, ZERO
HANDLE_ENTRY 1d, ZERO
HANDLE_ENTRY 1e, ZERO
HANDLE_ENTRY 1f, ZERO
HANDLE_ENTRY 20, ZERO ; 时钟中断对应的入口
HANDLE_ENTRY 21, ZERO ; 键盘中断对应的入口
HANDLE_ENTRY 22, ZERO ; 级联用的
HANDLE_ENTRY 23, ZERO ; 串口2对应的入口
HANDLE_ENTRY 24, ZERO ; 串口1对应的入口
HANDLE_ENTRY 25, ZERO ; 并口2对应的入口
HANDLE_ENTRY 26, ZERO ; 软盘对应的入口
HANDLE_ENTRY 27, ZERO ; 并口1对应的入口
HANDLE_ENTRY 28, ZERO ; 实时时钟对应的入口
HANDLE_ENTRY 29, ZERO ; 重定向
HANDLE_ENTRY 2a, ZERO ; 保留
HANDLE_ENTRY 2b, ZERO ; 保留
HANDLE_ENTRY 2c, ZERO ; ps/2鼠标
HANDLE_ENTRY 2d, ZERO ; fpu浮点单元异常
HANDLE_ENTRY 2e, ZERO ; 硬盘
HANDLE_ENTRY 2f, ZERO ; 保留
HANDLE_ENTRY 30, ZERO ;
HANDLE_ENTRY 31, ZERO ;
HANDLE_ENTRY 32, ZERO ;
HANDLE_ENTRY 33, ZERO ;
HANDLE_ENTRY 34, ZERO ;
HANDLE_ENTRY 35, ZERO ;
HANDLE_ENTRY 36, ZERO ;
HANDLE_ENTRY 37, ZERO ;
HANDLE_ENTRY 38, ZERO ;
HANDLE_ENTRY 39, ZERO ;
HANDLE_ENTRY 3a, ZERO ;
HANDLE_ENTRY 3b, ZERO ;
HANDLE_ENTRY 3c, ZERO ;
HANDLE_ENTRY 3d, ZERO ;
HANDLE_ENTRY 3e, ZERO ;
HANDLE_ENTRY 3f, ZERO ;
HANDLE_ENTRY 40, ZERO ; 系统调用
HANDLE_ENTRY 41, ZERO
HANDLE_ENTRY 42, ZERO
HANDLE_ENTRY 43, ZERO
HANDLE_ENTRY 44, ZERO
HANDLE_ENTRY 45, ZERO
HANDLE_ENTRY 46, ZERO
HANDLE_ENTRY 47, ZERO
HANDLE_ENTRY 48, ZERO
HANDLE_ENTRY 49, ZERO
HANDLE_ENTRY 4a, ZERO
HANDLE_ENTRY 4b, ZERO
HANDLE_ENTRY 4c, ZERO
HANDLE_ENTRY 4d, ZERO
HANDLE_ENTRY 4e, ZERO
HANDLE_ENTRY 4f, ZERO
HANDLE_ENTRY 50, ZERO
HANDLE_ENTRY 51, ZERO
HANDLE_ENTRY 52, ZERO
HANDLE_ENTRY 53, ZERO
HANDLE_ENTRY 54, ZERO
HANDLE_ENTRY 55, ZERO
HANDLE_ENTRY 56, ZERO
HANDLE_ENTRY 57, ZERO
HANDLE_ENTRY 58, ZERO
HANDLE_ENTRY 59, ZERO
HANDLE_ENTRY 5a, ZERO
HANDLE_ENTRY 5b, ZERO
HANDLE_ENTRY 5c, ZERO
HANDLE_ENTRY 5d, ZERO
HANDLE_ENTRY 5e, ZERO
HANDLE_ENTRY 5f, ZERO
HANDLE_ENTRY 60, ZERO
HANDLE_ENTRY 61, ZERO
HANDLE_ENTRY 62, ZERO
HANDLE_ENTRY 63, ZERO
HANDLE_ENTRY 64, ZERO
HANDLE_ENTRY 65, ZERO
HANDLE_ENTRY 66, ZERO
HANDLE_ENTRY 67, ZERO
HANDLE_ENTRY 68, ZERO
HANDLE_ENTRY 69, ZERO
HANDLE_ENTRY 6a, ZERO
HANDLE_ENTRY 6b, ZERO
HANDLE_ENTRY 6c, ZERO
HANDLE_ENTRY 6d, ZERO
HANDLE_ENTRY 6e, ZERO
HANDLE_ENTRY 6f, ZERO
HANDLE_ENTRY 70, ZERO
HANDLE_ENTRY 71, ZERO
HANDLE_ENTRY 72, ZERO
HANDLE_ENTRY 73, ZERO
HANDLE_ENTRY 74, ZERO
HANDLE_ENTRY 75, ZERO
HANDLE_ENTRY 76, ZERO
HANDLE_ENTRY 77, ZERO
HANDLE_ENTRY 78, ZERO
HANDLE_ENTRY 79, ZERO
HANDLE_ENTRY 7a, ZERO
HANDLE_ENTRY 7b, ZERO
HANDLE_ENTRY 7c, ZERO
HANDLE_ENTRY 7d, ZERO
HANDLE_ENTRY 7e, ZERO
HANDLE_ENTRY 7f, ZERO
HANDLE_ENTRY 80, ZERO
HANDLE_ENTRY 81, ZERO
HANDLE_ENTRY 82, ZERO
HANDLE_ENTRY 83, ZERO
HANDLE_ENTRY 84, ZERO
HANDLE_ENTRY 85, ZERO
HANDLE_ENTRY 86, ZERO
HANDLE_ENTRY 87, ZERO
HANDLE_ENTRY 88, ZERO
HANDLE_ENTRY 89, ZERO
HANDLE_ENTRY 8a, ZERO
HANDLE_ENTRY 8b, ZERO
HANDLE_ENTRY 8c, ZERO
HANDLE_ENTRY 8d, ZERO
HANDLE_ENTRY 8e, ZERO
HANDLE_ENTRY 8f, ZERO
HANDLE_ENTRY 90, ZERO
HANDLE_ENTRY 91, ZERO
HANDLE_ENTRY 92, ZERO
HANDLE_ENTRY 93, ZERO
HANDLE_ENTRY 94, ZERO
HANDLE_ENTRY 95, ZERO
HANDLE_ENTRY 96, ZERO
HANDLE_ENTRY 97, ZERO
HANDLE_ENTRY 98, ZERO
HANDLE_ENTRY 99, ZERO
HANDLE_ENTRY 9a, ZERO
HANDLE_ENTRY 9b, ZERO
HANDLE_ENTRY 9c, ZERO
HANDLE_ENTRY 9d, ZERO
HANDLE_ENTRY 9e, ZERO
HANDLE_ENTRY 9f, ZERO
HANDLE_ENTRY a0, ZERO
HANDLE_ENTRY a1, ZERO
HANDLE_ENTRY a2, ZERO
HANDLE_ENTRY a3, ZERO
HANDLE_ENTRY a4, ZERO
HANDLE_ENTRY a5, ZERO
HANDLE_ENTRY a6, ZERO
HANDLE_ENTRY a7, ZERO
HANDLE_ENTRY a8, ZERO
HANDLE_ENTRY a9, ZERO
HANDLE_ENTRY aa, ZERO
HANDLE_ENTRY ab, ZERO
HANDLE_ENTRY ac, ZERO
HANDLE_ENTRY ad, ZERO
HANDLE_ENTRY ae, ZERO
HANDLE_ENTRY af, ZERO
HANDLE_ENTRY b0, ZERO
HANDLE_ENTRY b1, ZERO
HANDLE_ENTRY b2, ZERO
HANDLE_ENTRY b3, ZERO
HANDLE_ENTRY b4, ZERO
HANDLE_ENTRY b5, ZERO
HANDLE_ENTRY b6, ZERO
HANDLE_ENTRY b7, ZERO
HANDLE_ENTRY b8, ZERO
HANDLE_ENTRY b9, ZERO
HANDLE_ENTRY ba, ZERO
HANDLE_ENTRY bb, ZERO
HANDLE_ENTRY bc, ZERO
HANDLE_ENTRY bd, ZERO
HANDLE_ENTRY be, ZERO
HANDLE_ENTRY bf, ZERO
HANDLE_ENTRY c0, ZERO
HANDLE_ENTRY c1, ZERO
HANDLE_ENTRY c2, ZERO
HANDLE_ENTRY c3, ZERO
HANDLE_ENTRY c4, ZERO
HANDLE_ENTRY c5, ZERO
HANDLE_ENTRY c6, ZERO
HANDLE_ENTRY c7, ZERO
HANDLE_ENTRY c8, ZERO
HANDLE_ENTRY c9, ZERO
HANDLE_ENTRY ca, ZERO
HANDLE_ENTRY cb, ZERO
HANDLE_ENTRY cc, ZERO
HANDLE_ENTRY cd, ZERO
HANDLE_ENTRY ce, ZERO
HANDLE_ENTRY cf, ZERO
HANDLE_ENTRY d0, ZERO
HANDLE_ENTRY d1, ZERO
HANDLE_ENTRY d2, ZERO
HANDLE_ENTRY d3, ZERO
HANDLE_ENTRY d4, ZERO
HANDLE_ENTRY d5, ZERO
HANDLE_ENTRY d6, ZERO
HANDLE_ENTRY d7, ZERO
HANDLE_ENTRY d8, ZERO
HANDLE_ENTRY d9, ZERO
HANDLE_ENTRY da, ZERO
HANDLE_ENTRY db, ZERO
HANDLE_ENTRY dc, ZERO
HANDLE_ENTRY dd, ZERO
HANDLE_ENTRY de, ZERO
HANDLE_ENTRY df, ZERO
HANDLE_ENTRY e0, ZERO
HANDLE_ENTRY e1, ZERO
HANDLE_ENTRY e2, ZERO
HANDLE_ENTRY e3, ZERO
HANDLE_ENTRY e4, ZERO
HANDLE_ENTRY e5, ZERO
HANDLE_ENTRY e6, ZERO
HANDLE_ENTRY e7, ZERO
HANDLE_ENTRY e8, ZERO
HANDLE_ENTRY e9, ZERO
HANDLE_ENTRY ea, ZERO
HANDLE_ENTRY eb, ZERO
HANDLE_ENTRY ec, ZERO
HANDLE_ENTRY ed, ZERO
HANDLE_ENTRY ee, ZERO
HANDLE_ENTRY ef, ZERO
HANDLE_ENTRY f0, ZERO
HANDLE_ENTRY f1, ZERO
HANDLE_ENTRY f2, ZERO
HANDLE_ENTRY f3, ZERO
HANDLE_ENTRY f4, ZERO
HANDLE_ENTRY f5, ZERO
HANDLE_ENTRY f6, ZERO
HANDLE_ENTRY f7, ZERO
HANDLE_ENTRY f8, ZERO
HANDLE_ENTRY f9, ZERO
HANDLE_ENTRY fa, ZERO
HANDLE_ENTRY fb, ZERO
HANDLE_ENTRY fc, ZERO
HANDLE_ENTRY fd, ZERO
HANDLE_ENTRY fe, ZERO
HANDLE_ENTRY ff, ZERO
[SECTION .data]
GLOBAL A
A: DQ 0