include ../build.ini
.PHONY: build
build:
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c asm.cpp 	  -o $(OBJECT_BUILD_PATH)/obj/asm.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c bit.cpp 	  -o $(OBJECT_BUILD_PATH)/obj/bit.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c utils.cpp 	  -o $(OBJECT_BUILD_PATH)/obj/utils.o