include ../../build.ini
.PHONY: build
build:
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c assert.cpp 	-o $(OBJECT_BUILD_PATH)/obj/assert.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c panic.cpp 	-o $(OBJECT_BUILD_PATH)/obj/panic.o