include ../../../build.ini
.PHONY: build
build:
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c ./cxxabi.cpp -o $(OBJECT_BUILD_PATH)/obj/cxxabi.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c ./builtins.cpp -o $(OBJECT_BUILD_PATH)/obj/builtins.o