include ../../build.ini
.PHONY: build
build:
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c ./Base/base_print.cpp -o $(OBJECT_BUILD_PATH)/obj/base_print.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c ./Format/core.cpp 	  -o $(OBJECT_BUILD_PATH)/obj/core.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c ./Format/format.cpp   -o $(OBJECT_BUILD_PATH)/obj/format.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c ./Stream/iostream.cpp -o $(OBJECT_BUILD_PATH)/obj/iostream.o