include ../../../build.ini
.PHONY: build
build:
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c ./CMOS.cpp 			-o $(OBJECT_BUILD_PATH)/obj/CMOS.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c ./ps2.cpp 			-o $(OBJECT_BUILD_PATH)/obj/ps2.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c ./timer.cpp 		-o $(OBJECT_BUILD_PATH)/obj/timer.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c ./fpu.cpp 			-o $(OBJECT_BUILD_PATH)/obj/fpu.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c ./device.cpp 		-o $(OBJECT_BUILD_PATH)/obj/device.o