include ../../build.ini
.PHONY: build
build:
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c allocate.cpp 			-o $(OBJECT_BUILD_PATH)/obj/allocate.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c bitmap.cpp              -o $(OBJECT_BUILD_PATH)/obj/bitmap.o
	$(GXX) $(C_CPP_INCLUDE_PATH) $(CPPFLAGS) -c symbol.cpp              -o $(OBJECT_BUILD_PATH)/obj/symbol.o